In [1]:
#installation (https://numpy.org/install/)

!conda install numpy
#!conda install numpy=1.20.2

Solving environment: done

# All requested packages already installed.



In [2]:
# import library and assign an alias

import numpy as np
print(np.__version__)

1.21.2


ARRAY OBJECT ATTRIBUTES

In [12]:

# ndarray object attributes (https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes)

n_d_array = np.array([[1,2,3],[4,5,6]])

#array es el método de numpy.

print(n_d_array, end='\n\n')
print(type(n_d_array))

print(n_d_array.ndim)   # number of array dimensions
print(n_d_array.shape)   # matrix's dimenssions size (i, j)
print(n_d_array.size)   # data buffer (i.e.: number of elements in the array)

print(n_d_array.dtype)   # https://numpy.org/doc/stable/reference/arrays.dtypes.html

print(n_d_array.itemsize)   # length of one array element in bytes 

[[1 2 3]
 [4 5 6]]

<class 'numpy.ndarray'>
2
(2, 3)
6
int64
8


ARRAY OBJECT METHODS

In [13]:
# Array conversion => .copy() --> Return a copy of the array.

copy = n_d_array.copy()
copy

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Array conversion => .tolist() --> Return the array as an a.ndim-levels deep nested list of Python scalars.

py_list = n_d_array.tolist()
py_list

[[1, 2, 3], [4, 5, 6]]

In [6]:
# Array conversion => .fill() --> Fill the array with a scalar value. Rellena con 8s.

n_d_array.fill(8)
n_d_array

array([[8, 8, 8],
       [8, 8, 8]])

In [15]:
# Shape manipulation => .reshape() --> Returns an array containing the same data with a new shape. Cambia la geometría según le indiquemos, aqui, hemos puesto que saque 3 filas y 2 columnas.


reshaped = n_d_array.reshape(3,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# Shape manipulation => .transpose() --> Returns a view of the array with axes transposed. Hace la traspuesta.
 
transposed = reshaped.transpose()
transposed

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
# Shape manipulation => .flatten() --> Return a copy of the array collapsed into one dimension.

flattened = n_d_array.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [18]:
# Calculation => .max() --> Return the maximum along a given axis.

max_ = n_d_array.max()
max_

6

In [19]:
# Calculation => .argmax() --> Returns the indices of the maximum values along an axis. Te dice la posición del máximo.

argmax_ = n_d_array.argmax()
argmax_

5

In [20]:
# Calculation => .sum() --> Sum of array elements over a given axis.

sum_ = n_d_array.sum()
sum_

21

Array creation routines

In [21]:
# numpy.arange() --> Return evenly spaced values within a given interval. Genera un array de los elementos que le indiquemos

array_range = np.arange(8)
array_range

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
# numpy.ones() --> Return a new array of given shape and type, filled with ones.

ones_array = np.ones((8,))
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# numpy.zeros() --> Return a new array of given shape and type, filled with zeros. El de la derecha indica el número de dimensiones, en este caso dos dimensiones, 8x5.

zeros_array = np.zeros((8,5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#Ver Indexing en Github

In [27]:
d1_array = np.arange(12)
d1_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
d2_array = d1_array.reshape((3,4))
d2_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
d3_array = d2_array.reshape((2,3,2))
d3_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
d3_array = np.zeros((3,3,3)) # + 10
d3_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
dn_array = np.arange(12).reshape((1, 2, 1, 6, 1))
dn_array

array([[[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]]],


        [[[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]]])

In [32]:
dn_array[0,1,0,0,0]

6

Slicing. Ver apuntes Github.

In [33]:
# Slicing (3,3)

slicing_array_3_3

NameError: name 'slicing_array_3_3' is not defined

In [34]:
# Slicing deep_dive (6,6)

slicing_array_6_6

NameError: name 'slicing_array_6_6' is not defined